"use client";

import { useMemo } from "react";

import { computeLineDiff } from "../../lib/line-diff";
import { ThemeRestoreActions } from "../shared/ThemeRestoreActions";

/**
 * Theme Guardian's visual inspection card (Sprint 5 Phase 3.2). Per the
 * user-approved approach (Option 1 — "honest text-diff, polished UI"): a
 * real side-by-side Liquid diff of the actual baseline vs. current file
 * content already on this Issue's `evidence_data`, never a synthetic
 * screenshot NightShift never actually captured.
 *
 * Header banner note: the approved spec called for labeling this "Gemini
 * 1.5 Pro's structured analysis." That model name is retired (see
 * CONFLICTS.md item 12) and this codebase has no per-issue
 * model/provider attribution field at all (CONFLICTS.md item 15). Naming a
 * specific model version here would be a fabricated attribution, so the
 * banner is labeled neutrally ("NightShift AI Analysis") instead — see
 * CONFLICTS.md item 49.
 */

interface ThemeGuardianEvidence {
  filename: string;
  themeId: string;
  baselineContent: string;
  currentContent: string;
}

function readEvidence(evidenceData: Record<string, unknown> | null | undefined): ThemeGuardianEvidence | null {
  if (!evidenceData) return null;
  if (evidenceData["fix_check"] !== "theme_file_diverged_from_baseline") return null;

  const filename = evidenceData["filename"];
  const themeId = evidenceData["theme_id"];
  const baselineContent = evidenceData["baseline_content"];
  const currentContent = evidenceData["current_content"];
  if (
    typeof filename !== "string" ||
    typeof themeId !== "string" ||
    typeof baselineContent !== "string" ||
    typeof currentContent !== "string"
  ) {
    return null;
  }
  return { filename, themeId, baselineContent, currentContent };
}

/** Mirrors `execute_cognitive_task.py`'s exact theme_restore_guide URL
 * construction (`https://admin.shopify.com/store/{handle}/themes/{id}`) —
 * same deterministic string, computed here so the guided-resolution action
 * area is available immediately, before a merchant has approved anything
 * (theme file writes are never autonomous — CONFLICTS.md item 38 — so
 * there's no execution step this needs to wait for). */
function themeEditorUrl(shopDomain: string, themeGid: string): string {
  const storeHandle = shopDomain.replace(/\.myshopify\.com$/, "");
  const themeNumericId = themeGid.includes("/") ? themeGid.split("/").pop() : themeGid;
  return `https://admin.shopify.com/store/${storeHandle}/themes/${themeNumericId}`;
}

export function ThemeGuardianDiffCard({
  shopDomain,
  description,
  evidenceData,
}: {
  shopDomain: string | null;
  description: string;
  evidenceData: Record<string, unknown> | null | undefined;
}) {
  const evidence = useMemo(() => readEvidence(evidenceData), [evidenceData]);
  const diff = useMemo(
    () => (evidence ? computeLineDiff(evidence.baselineContent, evidence.currentContent) : null),
    [evidence]
  );

  if (!evidence) return null;

  return (
    <div className="mt-3 space-y-3 rounded-lg border border-gray-800 bg-gray-950 p-4">
      {/* Header banner: the specialist's own plain-English explanation of
          storefront impact — real content already generated by Theme
          Guardian (LLM-authored or its deterministic fallback, see
          `domain/agents/theme_guardian.py`), never re-summarized here. */}
      <div className="rounded-md border border-gray-800 bg-gray-900 p-3">
        <p className="text-[11px] font-semibold uppercase tracking-wide text-gray-500">
          🛡️ Theme Guardian — NightShift AI Analysis
        </p>
        <p className="mt-1 text-sm text-gray-200">{description}</p>
      </div>

      <p className="font-mono text-xs text-gray-500">{evidence.filename}</p>

      {diff ? (
        <div className="grid grid-cols-1 gap-px overflow-hidden rounded-md border border-gray-800 bg-gray-800 sm:grid-cols-2">
          <div className="bg-gray-950">
            <p className="border-b border-gray-800 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wide text-gray-500">
              Baseline (last known-good)
            </p>
            <pre className="max-h-80 overflow-auto p-3 font-mono text-xs leading-relaxed">
              {diff.map((line, i) =>
                line.type === "added" ? null : (
                  <div
                    key={i}
                    className={line.type === "removed" ? "bg-red-950/60 text-red-300" : "text-gray-300"}
                  >
                    {line.content || " "}
                  </div>
                )
              )}
            </pre>
          </div>
          <div className="bg-gray-950">
            <p className="border-b border-gray-800 px-3 py-1.5 text-[11px] font-semibold uppercase tracking-wide text-gray-500">
              Current (live)
            </p>
            <pre className="max-h-80 overflow-auto p-3 font-mono text-xs leading-relaxed">
              {diff.map((line, i) =>
                line.type === "removed" ? null : (
                  <div
                    key={i}
                    className={line.type === "added" ? "bg-emerald-950/60 text-emerald-300" : "text-gray-300"}
                  >
                    {line.content || " "}
                  </div>
                )
              )}
            </pre>
          </div>
        </div>
      ) : (
        // Guard-rail fallback for a pathologically large file (line-diff.ts's
        // own size cap) — never hangs the tab, just skips highlighting.
        <p className="text-xs text-gray-500">File too large to highlight line-by-line here.</p>
      )}

      {shopDomain ? (
        <ThemeRestoreActions
          filename={evidence.filename}
          themeEditorUrl={themeEditorUrl(shopDomain, evidence.themeId)}
          patchContent={evidence.baselineContent}
        />
      ) : null}
    </div>
  );
}
